spring.application.name=bookmyroom

spring.datasource.url=jdbc:mysql://localhost:3306/bookmyroom?useSSL=false&serverTimezone=Asia/Kolkata
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080